# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: .circleci/solution_check.yml
          mapping: |
            day_01/.+ day_1 true
            day_02/.+ day_2 true 
            day_03/.+ day_3 true
            day_04/.+ day_4 true
            day_05/.+ day_5 true
            day_07/.+ day_7 true
            day_08/.+ day_8 true
            day_10/.+ day_10 true
            day_11/.+ day_11 true
            day_13/.+ day_13 true
