version: 2.1

parameters: 
  day_1:
    type: boolean
    default: false
  day_2:
    type: boolean
    default: false
  day_3:
    type: boolean
    default: false
  day_4:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: rust:1.81
    parameters:
      directory:
        type: string
    steps:
      - checkout
      - run:
          name: "Cargo test"
          command: "cargo test"
          working_directory: << parameters.directory >>
  lint:
    docker:
      - image: rust:1.81
    parameters:
      directory:
        type: string
    steps:
      - checkout
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: << parameters.directory >>
      - run:
          name: "Lint"
          command: "cargo clippy --no-deps -- -Dwarnings"
          working_directory: << parameters.directory >>

workflows:
  day_1:
    when: << pipeline.parameters.day_1 >>
    jobs:
      - test:
          directory: day_01
      - lint:
          directory: day_01
  day_2:
    when: << pipeline.parameters.day_2 >>
    jobs:
    - test:
        directory: day_02
    - lint:
          directory: day_02
  day_3:
    when: << pipeline.parameters.day_3 >>
    jobs:
    - test:
        directory: day_03
    - lint:
          directory: day_03
  day_4:
    when: << pipeline.parameters.day_4 >>
    jobs:
    - test:
        directory: day_04
    - lint:
          directory: day_04
