version: 2.1

parameters: 
  day_1:
    type: boolean
    default: false
  day_2:
    type: boolean
    default: false
  day_3:
    type: boolean
    default: false
  day_4:
    type: boolean
    default: false
  day_5:
    type: boolean
    default: false
  day_7:
    type: boolean
    default: false
  day_8:
    type: boolean
    default: false
  day_10:
    type: boolean
    default: false
  day_11:
    type: boolean
    default: false
  day_13:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: rust:1.81
    parameters:
      directory:
        type: string
    steps:
      - checkout
      - run:
          name: "Cargo test"
          command: "cargo test"
          working_directory: << parameters.directory >>
  lint:
    docker:
      - image: rust:1.81
    parameters:
      directory:
        type: string
    steps:
      - checkout
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: << parameters.directory >>
      - run:
          name: "Lint"
          command: "cargo clippy --no-deps --all-targets -- -Dwarnings"
          working_directory: << parameters.directory >>

workflows:
  day_1:
    when: << pipeline.parameters.day_1 >>
    jobs:
      - test:
          directory: day_01
      - lint:
          directory: day_01
  day_2:
    when: << pipeline.parameters.day_2 >>
    jobs:
    - test:
        directory: day_02
    - lint:
          directory: day_02
  day_3:
    when: << pipeline.parameters.day_3 >>
    jobs:
    - test:
        directory: day_03
    - lint:
          directory: day_03
  day_4:
    when: << pipeline.parameters.day_4 >>
    jobs:
    - test:
        directory: day_04
    - lint:
          directory: day_04
  day_5:
    when: << pipeline.parameters.day_5 >>
    jobs:
    - test:
        directory: day_05
    - lint:
          directory: day_05
  day_7:
    when: << pipeline.parameters.day_7 >>
    jobs:
    - test:
        directory: day_07
    - lint:
          directory: day_07
  day_8:
    when: << pipeline.parameters.day_8 >>
    jobs:
    - test:
        directory: day_08
    - lint:
          directory: day_08
  day_10:
    when: << pipeline.parameters.day_10 >>
    jobs:
    - test:
        directory: day_10
    - lint:
          directory: day_10
  day_11:
    when: << pipeline.parameters.day_11 >>
    jobs:
    - test:
        directory: day_11
    - lint:
          directory: day_11
  day_13:
    when: << pipeline.parameters.day_13 >>
    jobs:
    - test:
        directory: day_13
    - lint:
          directory: day_13
